/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.9
<<<<<<< HEAD
<<<<<<< HEAD
 * Generated at: 2026-04-24 02:58:25 UTC
=======
 * Generated at: 2026-04-24 02:59:25 UTC
>>>>>>> f3a07ca3bb2c9b74f11e1ceee04a5ca541f89310
=======
 * Generated at: 2026-04-24 03:21:48 UTC
>>>>>>> 995a5ca9849614984fc6cdc3467548e0aa0b7359
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.auth;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>メニュー</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        background-color: #f8f9fa;\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("        background-color: #dee2e6;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    p {\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        box-shadow: 0 4px 10px rgba(0,0,0,0.08);\r\n");
      out.write("        transition: 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    p:hover {\r\n");
      out.write("        transform: translateY(-3px);\r\n");
      out.write("        box-shadow: 0 8px 16px rgba(0,0,0,0.12);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    p a {\r\n");
      out.write("        display: block;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    .logout-btn {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 20px;\r\n");
      out.write("        right: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 色分け（HTMLそのまま） */\r\n");
      out.write("    p:nth-of-type(1) {\r\n");
      out.write("        background-color: #f8d7da;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    p:nth-of-type(2),\r\n");
      out.write("    p:nth-of-type(3) {\r\n");
      out.write("        background-color: #d1e7dd;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    p:nth-of-type(4) {\r\n");
      out.write("        background-color: #d6d8f5;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h2>メニュー画面</h2>\r\n");
      out.write("<div class=\"text-end mb-3\">\r\n");
      out.write("    <a class=\"btn btn-warning\"\r\n");
      out.write("       href=\"Logout.action\"\r\n");
      out.write("       onclick=\"return confirm('ログアウトしますか？');\">\r\n");
      out.write("       ログアウト\r\n");
      out.write("    </a>\r\n");
      out.write("</div>\r\n");
      out.write("<p><a href=\"student.action\">学生管理</a></p>\r\n");
      out.write("<p><a href=\"testRegist.action\">成績参照</a></p>\r\n");
      out.write("<p><a href=\"testList.action\">成績登録</a></p>\r\n");
      out.write("<p><a href=\"subjectList.action\">科目管理</a></p>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
